version: 2.1

jobs:
  build:
    working_directory: ~/circleci-javascript
    docker:
      - image: "circleci/node:14.17"
    steps:
      - checkout
      - run: npm install
      - run: node main.js
  test:
    working_directory: ~/circleci-javascript
    docker:
      - image: "circleci/node:14.17"
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
